_target_: pytorch_lightning.Trainer

accelerator: gpu
devices: [6]
num_nodes: 1
num_sanity_val_steps: 2
fast_dev_run: True
#min_epochs: 1
#max_epochs: 30
check_val_every_n_epoch: 1
resume_from_checkpoint: null
detect_anomaly: True
gradient_clip_val: 0.5
profiler: simple