_target_: pytorch_lightning.Trainer
accelerator: gpu
devices: 4
num_nodes: 1
min_epochs: 1
max_epochs: 5
limit_train_batches: 50
limit_val_batches: 5
check_val_every_n_epoch: 1
resume_from_checkpoint: null