_target_: src.models.copydetect_module.CopyDetectModule
pretrained_arch: 'google/vit-base-patch16-224'
lr: 0.001
weight_decay: 0.0005
hidden_dim: 2048
projected_dim: 512

ntxentloss:
  _target_: src.utils.nt_xent_loss.NTXentLoss
  temperature: 0.9
  eps: 1e-5
