_target_: src.models.copydetect_module.CopyDetectModule
pretrained_arch: 'google/vit-base-patch16-224'
#lr: 0.0002
lr: 0.0001
gamma1: 1
gamma2: 1
beta1: 0.9
beta2: 0.999
weight_decay: 0
hidden_dim: 1024
projected_dim: 256
t_initial: 5
k_decay: 1
warmup_t: 10
warmup_lr_init: 0.01

ntxentloss:
  _target_: src.utils.nt_xent_loss.NTXentLoss
  temperature: 0.1
  eps: 1e-5
