_target_: src.models.copydetect_module.CopyDetectModule
pretrained_arch: 'google/vit-base-patch16-224'
lr: 0.0002
gamma1: 1
gamma2: 1
beta1: 0.9
beta2: 0.999
weight_decay: 0
hidden_dim: 1024
projected_dim: 256
warmup_min_lr: 0.01
warmup_num_steps: 10000

ntxentloss:
  _target_: src.utils.nt_xent_loss.NTXentLoss
  temperature: 0.1
  eps: 1e-5
