model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "val/acc"
  mode: "max"
  save_top_k: 1
  verbose: False
  dirpath: "checkpoints/"
  filename: "epoch_{epoch:03d}"
  auto_insert_metric_name: False
  every_n_epochs: 3

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: "val/acc" 
  mode: "max" 
  patience: 25

rich_progress_bar:
  _target_: pytorch_lightning.callbacks.RichProgressBar

device_stats:
  _target_: pytorch_lightning.callbacks.DeviceStatsMonitor

stochastic_weight_averaging:
  _target_: pytorch_lightning.callbacks.StochasticWeightAveraging
  swa_epoch_start: 0.8 
  swa_lrs: None