# @package _global_

defaults:
  - _self_
  - datamodule: copydetect.yaml
  - model: copydetect.yaml
  - callbacks: default.yaml
  - logger: wandb.yaml
  - trainer: default.yaml
  - log_dir: default.yaml
  - experiment: null
  - debug: null
  - hparams_search: null
  - optional local: default.yaml

  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}
data_dir: ${original_work_dir}/data/
print_config: True
ignore_warnings: True
train: True
test: False
seed: null
name: "copydetection"
