
_target_: src.datamodules.copydetect_datamodule.CopyDetectDataModule

#training_dir: ${data_dir}/training/
train_dir: ${data_dir}/train/
references_dir: ${data_dir}/references/
dev_queries_dir: ${data_dir}/dev_queries/
final_queries_dir:  ${data_dir}/final_queries/
dev_validation_set: ${data_dir}/dev_validation_set.csv
dev_ground_truth: ${data_dir}/dev_ground_truth.csv
batch_size: 128
num_workers: 20
pin_memory: True
n_crops: 4
image_size: 224

augment:
  _target_: src.datamodules.components.augmentation.Augment
  overlay_image_dir: ${data_dir}/train
  n_upper: 6
  n_lower: 4