# @package _global_

defaults:
  - override /log_dir: debug.yaml

trainer:
  fast_dev_run: true
  gpus: 0 
  detect_anomaly: true 
  track_grad_norm: 2 

datamodule:
  num_workers: 0 
  pin_memory: False

hydra:
  verbose: True

print_config: False
